version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: remove_old_files.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/change_permissions.sh
#       timeout: 300
#       runas: root
  ApplicationStart:
      - location: start_jars.sh
#     - location: scripts/create_test_db.sh
#       timeout: 300
#       runas: root
  ApplicationStop:
     - location: stop_jars.sh
#       timeout: 300
#       runas: root