version: '3.7'


# Define services
services:
    order_products_and_receive_ordered_products:
        build:
            context: ./orderProductsAndReceiveOrderedProducts
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
        extra_hosts:
          - "theDB:127.0.0.1"
    
    show_delivery_reports:
        build:
            context: ./showDeliveryReports
            dockerfile: Dockerfile
        ports: 
            - "8086:8086"
        extra_hosts:
            - "theDB:127.0.0.1"

    show_stock_reports:
        build:
            context: ./showStockReports
            dockerfile: Dockerfile
        ports:
            - "8085:8085"
        extra_hosts:
            - "theDB:127.0.0.1"

    api_gateway:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        extra_hosts:
            - "theDB:127.0.0.1"